
const ActionType = {
  APP_INIT: 'APP_INIT',
  SET_REDIRECT_URL: 'SET_REDIRECT_URL',
  PAGE_REDIRECTED: 'PAGE_REDIRECTED',

  INIT_CUSTOMER_SESSION: 'INIT_CUSTOMER_SESSION',
  INIT_CUSTOMER_SESSION_SUCCESS: 'INIT_CUSTOMER_SESSION_SUCCESS',
  INIT_CUSTOMER_SESSION_FAILED: 'INIT_CUSTOMER_SESSION_FAILED',

  CUSTOMER_SUBMIT_LOAN: 'CUSTOMER_SUBMIT_LOAN',
  CUSTOMER_SUBMIT_LOAN_SUCCESS: 'CUSTOMER_SUBMIT_LOAN_SUCCESS',
  CUSTOMER_SUBMIT_LOAN_FAILED: 'CUSTOMER_SUBMIT_LOAN_FAILED',
  CUSTOMER_SUBMIT_LOAN_CLEAR_DATA: 'CUSTOMER_SUBMIT_LOAN_CLEAR_DATA',

  API_ERROR_INTERNAL_SERVER_ERROR: 'API_ERROR_INTERNAL_SERVER_ERROR',
  API_ERROR_UNAUTHORIZED: 'API_ERROR_UNAUTHORIZED',
  API_ERROR_FORBIDDEN: 'API_ERROR_FORBIDDEN',
  API_ERROR_NETWORK_ERROR: 'API_ERROR_NETWORK_ERROR',

  GET_LOAN_CONFIG: 'GET_LOAN_CONFIG',
  GET_LOAN_CONFIG_SUCCESS: 'GET_LOAN_CONFIG_SUCCESS',
  GET_LOAN_CONFIG_FAILED: 'GET_LOAN_CONFIG_FAILED',

  GET_DECISION_STATUS: 'GET_DECISION_STATUS',
  GET_DECISION_STATUS_SUCCESS: 'GET_DECISION_STATUS_SUCCESS',
  GET_DECISION_STATUS_FAILED: 'GET_DECISION_STATUS_FAILED',
  GET_LOAN_CONFIG_AUTO: 'GET_LOAN_CONFIG_AUTO',
  GET_DECISION_STATUS_CLEAR_DATA: 'GET_DECISION_STATUS_CLEAR_DATA',

  REVOKE_CUSTOMER_SESSION: 'REVOKE_CUSTOMER_SESSION',
  REVOKE_CUSTOMER_SESSION_SUCCESS: 'REVOKE_CUSTOMER_SESSION_SUCCESS',
  REVOKE_CUSTOMER_SESSION_FAILED: 'REVOKE_CUSTOMER_SESSION_FAILED',

  GET_COMPANY_NAME: 'GET_COMPANY_NAME',
  GET_COMPANY_NAME_DONE: 'GET_COMPANY_NAME_DONE',
  CLEAR_COMPANY_NAME: 'CLEAR_COMPANY_NAME',

  GET_PREDICT_DATA_LIST: 'GET_PREDICT_DATA_LIST',
  GET_PREDICT_DATA_LIST_SUCCESS:'GET_PREDICT_DATA_LIST_SUCCESS',

  LOG_TIME: 'LOG_TIME',

  RESET_APP: 'RESET_APP'
}

export default ActionType
